# Language setting
language: node_js

# Version number
node_js:
  - 0.10.25

# Create directories for test and coverage reports
before_script:
  - ./node_modules/.bin/bower install
#   - mkdir -p shippable/testresults

# Running the tests with ember
script:
  - ./node_modules/.bin/ember test
  #  > shippable/testresults/result.xml
